### ISSUE TITLE
Mushclient-Consider issues

### ISSUE THREAD

**Issue by Khrysis-aard** [Shindo-Aardwolf/Mushclient-Consider#1]
auras don't  seem to show up except in the mouse over on the mini window
cant determine 2.mob 3.mob if more than one mob in room has the same name
the mini window is no longer clickable like in older versions not sure if this was intended or just got broke later

**Comment by Shindo-Aardwolf** [comment]
3. The clickable mini-window is something i need to investigate because that I didn't mean to break but as you said it is now broken.

2. I have no problem with multiple mobs with the same keywords HOWEVER in some places the short name of the mob contains words that are not part of the mobs keywords, The servants in Adaldar are an example of this. Most of those mob names can be cleaned up in Name_Cleanup.lua, there are a few examples already in there on how to do that. I'm not at a level of coding to build a database that does all that interactively. If someone would like to add that they are welcome to.

1. Auras, yeah they are an issue, if i recall correctly it's because i just used the consider from all the S&D plugins and never built it to show them (yes, i'm lazy)

**Comment by Khrysis-aard** [comment]
ok fixed the clickable window part

execute_command in Show_window function needs to be Execute_command instead

far as the flags prob i am not sure though

**Comment by Shindo-Aardwolf** [comment]
OMG, so it was my fault that broke... lets just blame the switch to VSCode.

I'm pushing the fix for hot clickable areas now

**Comment by Khrysis-aard** [comment]
function Process_flags (flags)
	local newflags = ''
	if string.find(flags,"%(W%)") or
           string.find(flags,"%(White Aura%)") then
		newflags = newflags.. "@x015(W)"
	else
		newflags = newflags.. "   "
	end
	if string.find(flags,"%(R%)") or
           string.find(flags,"%(Red Aura%)") then
		newflags = newflags.. "@x001(R)"
	elseif string.find(flags,"%(G%)") or
               string.find(flags,"%(Golden Aura%)") then
		newflags = newflags.. "@x003(G)"
	else
		newflags = newflags.. "   "
	end

	return newflags
end


This will fix it if u don't have shortflags on which was entirely the problem.
Thanks goes out to Adaldag who helped me find this issue then we came up with the fix for it to work either way but still left it
putting the short version in the conw itself to save space. But with this in there it will work with shortflags on or off doesnt matter which

**Comment by Shindo-Aardwolf** [comment]
Thanks for the help finding and fixing these two issues.  I had misunderstood what you meant about the flags so would never have thought of the long flags version of the problem.
I'm going to mark this issue as closed.
